apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: word-count
  namespace: spark
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: {{ACCOUNTNUMBER}}.dkr.ecr.{{REGION}}.amazonaws.com/arc:latest
  imagePullPolicy: Always
  mainApplicationFile: "s3a://{{codeBucket}}/app_code/job/wordcount.py"
  arguments: ["s3a://{{codeBucket}}/app_code/output/native"]
  sparkVersion: "3.0.1"
  sparkConf:
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.aws.credentials.provider": "com.amazonaws.auth.WebIdentityTokenCredentialsProvider"
    "spark.kubernetes.allocation.batch.size": "10" 
    "spark.io.encryption.enabled": "true"
    "spark.kubernetes.local.dirs.tmpfs": "true"
  driver:
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:  
          nodeSelectorTerms:
              - matchExpressions:
                - key: lifecycle 
                  operator: In 
                  values: 
                  - OnDemand
  executor:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:     
          nodeSelectorTerms:
                - matchExpressions:
                  - key: lifecycle 
                    operator: In 
                    values: 
                    - Ec2Spot           
  volumes:
    - name: spark-local-dir-1
      hostPath:
        path: "/tmp"
        type: Directory      
  dynamicAllocation:
    enabled: true
    initialExecutors: 1
    minExecutors: 1
    maxExecutors: 20
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    memory: "1G"
    labels:
      role: driver
    serviceAccount: nativejob
    volumeMounts:
      - name: spark-local-dir-1
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 10
    memory: "4G"
    labels:
      role: executor
    volumeMounts:
      - name: spark-local-dir-1
        mountPath: "/tmp"
