kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: etl-workflow-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "list", "get", "delete", "watch", "patch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["create", "get", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete"]  
- apiGroups: [""]
  resources: ["nodes/proxy"]
  verbs: ["get"]  

---  
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: etl-rolebinding
subjects:
- kind: ServiceAccount
  name: etl
  namespace: argo  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: etl-workflow-role