autoDiscovery:
    clusterName: eksctl-managed
awsRegion: us-west-2
image:
    tag: v1.17.3
podAnnotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
podLabels:
    app: spark
rbac:
    serviceAccount:
        create: false
        name: cluster-autoscaler
  