kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: etl-workflow-role
  namespace: spark
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "list", "get", "delete", "watch", "patch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["create", "get", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "delete"]
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["get"]
  
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: etl-role-binding
  namespace: spark
subjects:
  - kind: ServiceAccount
    name: arcjob
    namespace: spark
roleRef:
  kind: Role
  name: etl-workflow-role
  apiGroup: rbac.authorization.k8s.io