apiVersion: v1
kind: Pod
metadata:
  labels:
    spark-role: executor
  namespace: spark
spec:
  serviceAccountName: nativejob
  affinity: 
      nodeAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
            nodeSelectorTerms:
            - matchExpressions:
              - key: lifecycle 
                operator: In 
                values: 
                - Ec2Spot
      podAffinity:          
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: lifecycle
                  operator: In
                  values:
                  - Ec2Spot
              topologyKey: topology.kubernetes.io/zone