
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jupyter-external-secret
  namespace: jupyter
spec:
  backendType: secretsManager
  region: {{region}}
  data:
    - key: jHubPwd6E48ECC3-0YhYd3BbaFH5
      name: password
      property: password          
