hub:
  db:
    type: sqlite-memory
  extraConfig:
    overrideServiceAccount: |
      # this script allows serviceAccountName to use dynamic naming based on {username}"
      async def override_service_account_hook(kube_spawner):
        if kube_spawner.service_account is not None:
          kube_spawner.service_account = kube_spawner._expand_user_properties(kube_spawner.service_account)

      c.KubeSpawner.pre_spawn_hook = override_service_account_hook

proxy:
  secretToken: "37d978c42bd042da78a1afa5a32dacaaee863ded4926eca2b30cc3005832d636"
  service:
    type: ClusterIP
   
# ingress:
#   enabled: true
#   hosts:
#     - ""
#   annotations:
#     kubernetes.io/ingress.class: alb
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: ip
#     alb.ingress.kubernetes.io/success-codes: 200,301,302
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8000}]'
#   labels:
#     app: jupyterhub

auth:
  dummy:
    password: "password"

singleuser:
  defaultUrl: "/lab"
  image:
    name: ghcr.io/tripl-ai/arc-jupyter
    tag: latest
    pullPolicy: IfNotPresent
  lifecycle_hooks:
    postStart:
      exec:
        command: ["cp", "-r", "/opt/.jupyter", "/home/jovyan/.jupyter"]  
  serviceAccountName: "{username}"
  storage:
    type: none
  # Default Resource Limits/Guarantees
  cpu:
    guarantee: 0.25
    limit: 0.5
  memory:
    guarantee: 4G
    limit: 4G
  extraEnv:
    JAVA_OPTS: -Xmx4G
  # extraSecurityContext:
  #   runAsUser: 65534
  #   fsGroup: 65534
  #   allowPrivilegeEscalation: false  
  # storage:
  #   capacity: 50G
  #   type: dynamic
  #   dynamic:
  #     storageClass: csi-sc
  profileList:
  - default: True
    display_name: "1. 4GB Memory & 1vCPUs"
    description: "Small (default): Arc-Jupyter Development Environment"
    kubespawner_override:
      cpu_guarantee: 0.5
      cpu_limit: 1
      mem_guarantee: 4G
      mem_limit: 15G
  - display_name: "2. 15GB Memory & 2vCPUs"
    description: "Big Arc-Jupyter Development Environment"
    kubespawner_override:
      cpu_guarantee: 0.5
      cpu_limit: 2
      mem_guarantee: 10G
      mem_limit: 15G