hub:
  db:
    type: sqlite-memory
  extraConfig:
    overrideServiceAccount: |
      # this script allows serviceAccountName to use dynamic naming based on {username}"
      async def override_service_account_hook(kube_spawner):
        if kube_spawner.service_account is not None:
          kube_spawner.service_account = kube_spawner._expand_user_properties(kube_spawner.service_account)

      c.KubeSpawner.pre_spawn_hook = override_service_account_hook

proxy:
  secretToken: "37d978c42bd042da78a1afa5a32dacaaee863ded4926eca2b30cc3005832d636"
  service:
    type: ClusterIP
auth:
  dummy:
    password: "password"

singleuser:
  image:
    name: triplai/arc-jupyter
    tag: latest
    pullPolicy: IfNotPresent
  serviceAccountName: "{username}"
  storage:
    type: none
  memory:
    limit: 4G
    guarantee: 4G
  extraEnv:
    JAVA_OPTS: -Xmx4G
  # storage:
  #   capacity: 50G
  #   type: dynamic
  #   dynamic:
  #     storageClass: csi-sc
  profileList:
  - default: True
    description: "Small (default): Arc-Jupyter Development Environment"
    display_name: |
      A small serverless (Fargate) instance. 4GB Memory & 4vCPUs
    kubespawner_override:
      image: 'triplai/arc-jupyter:latest'
      ports:
        - containerPort: 8080
      lifecycle_hooks:
        postStart:
          exec:
            command: ["cp", "-r", "/opt/.jupyter", "/home/jovyan/.jupyter"]

    # - display_name: "Big: Arc-Jupyter Development Environment"
    #   description: |
    #     A big serverless (Fargate) instance. 30GB Memory & 4 vCPUs
    #   kubespawner_override:
    #     image: ghcr.io/tripl-ai/arc-jupyter:latest
    #     ports:
    #       - containerPort: 8080
    #     mem_limit: 30G
    #     mem_guaranttee: 30G
    #     extra_resource_limits:
    #       JAVA_OPTS: -Xmx8G
    #     # copy in the notebook customisations
    #     lifecycle_hooks:
    #       postStart:
    #         exec:
    #           command: ["cp", "-r", "/opt/.jupyter", "/home/jovyan/.jupyter"]