kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{MY_SA}}-role-binding
  namespace: jupyter
subjects:
  - kind: ServiceAccount
    name: {{MY_SA}}
    namespace: jupyter
roleRef:
  kind: Role
  name: hub
  apiGroup: rbac.authorization.k8s.io