apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  # need it if using ArgoCLI
  generateName: scd2-job-
  namespace: spark
  ## need it if use kubectl
  # name: scd2-job
spec:
  serviceAccountName: arcjob
  entrypoint: scd2-load
  ## must complete in 8h
  activeDeadlineSeconds: 28800
  # keep workflows for 12h (43,200 seconds)
  ttlStrategy:
    secondsAfterCompletion: 43200
    SecondsAfterFailure: 43200
  templates:
  - name: scd2-load
    dag:
      tasks:
        - name: delta-load-SCD2
          templateRef:
            name: spark-template
            template: mediumJob
            clusterScope: true 
          arguments:
            parameters:
            - name: jobId
              value: scd2 
            - name: image
              value: ghcr.io/tripl-ai/arc:latest
            ## in the sample jupyter notebook, all stages will be run in test and prod only.
            - name: environment
              value: test   
            - name: tags
              value: "project=sqlbasedetl, owner=myang, costcenter=66666"     
            - name: configUri
              value: "s3a://testtestmelody/app-code/job/auto_job.ipynb"
            - name: parameters
              value: "--ETL_CONF_DATALAKE_LOC=testtestmelody"